version: '3.8'

services:
  proj1:
    build:
      context: .
      dockerfile: proj1/Dockerfile
    command: "python server.py && python client.py"
    ports:
      - "9005:9005"
    volumes:
      - .:/proj1
    restart: always


  proj2:
    build:
      context: .
      dockerfile: proj2/Dockerfile
    command: "python server.py && python client.py"
    ports:
      - "9006:9006"
    volumes:
     - .:/proj2
    restart: always

  proj3:
    build:
      context: .
      dockerfile: proj3/Dockerfile
    command: "python server.py && python client.py"
    ports:
      - "9007:9007"
    volumes:
     - .:/proj3
    restart: always
