import grpc
import hello_world_pb2 # generated by grpc tools
import hello_world_pb2_grpc # generated by grpc tools

def run():
    '''
    create connection
    '''
    with grpc.insecure_channel('0.0.0.0:9006') as channel:
        stub = hello_world_pb2_grpc.HelloWorldServiceStub(channel) # stub creates a connection. serialize the input paramaters send the request to the server, receives the response and deserialize it into the appropriate data structure. 
        request = hello_world_pb2.HelloRequest()
        request.req_msg = "Requested from project 1" # req_msg field, defined in proto file message:HelloRequest 
        response = stub.SayHello(request)
        print(f"Response from project 2:\n{ response.res_msg }")


if __name__=='__main__':
    run()