import grpc
import hello_world_pb2 # generated by grpc tools
import hello_world_pb2_grpc # generated by grpc tools
from concurrent import futures

from py_code.helloworld import hello_world as hello_world

class HelloMessage(hello_world_pb2_grpc.HelloWorldService):
    def SayHello(self, request, context): # SayHello defined in protofile
        msg = request.req_msg # req_msg field, defined in proto file message:HelloRequest 
        respnse = hello_world_pb2.HelloResponse()
        respnse.res_msg = hello_world(msg) # res_msg field, defined in proto file message:HelloResponse
        return respnse
    

def server():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    hello_world_pb2_grpc.add_HelloWorldServiceServicer_to_server(HelloMessage(), server)
    server.add_insecure_port('[::]:9005')
    server.start()
    print("Project-1 Server started, listening on " + '9005')
    server.wait_for_termination()


if __name__ == '__main__':
    server()